board := "esp32:esp32:XIAO_ESP32S3"
port := "/dev/ttyACM0"
sketch := "firmware"

install:
  curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | BINDIR=/usr/bin sh
  arduino-cli config add board_manager.additional_urls https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
  arduino-cli core install esp32:esp32

compile:
  arduino-cli compile -b {{board}} {{sketch}}

upload: compile
  arduino-cli upload -b {{board}} -p {{port}} {{sketch}}

monitor:
  arduino-cli monitor -p {{port}} -c baudrate=115200
